-- ============================================================================
-- PostgreSQL 17 — 新增「MatchLogSets」友誼賽動態局分子表
-- ----------------------------------------------------------------------------
-- 背景：友誼賽可能同一個對手連續打 6~9 局，原 MatchLogs 表 Set1/Set2/Set3
--       三欄無法承載。新增子表，僅 MatchEvent.MatchType=Friendly 時寫入；
--       Official 賽事仍沿用 MatchLogs 的固定欄位。
-- 冪等：表 / FK / 索引一律使用 IF NOT EXISTS。
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS "MatchLogSets" (
    "Id"              integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MatchLogId"      integer       NOT NULL,
    "SetIndex"        smallint      NOT NULL,
    "OurScore"        integer       NOT NULL,
    "OpponentScore"   integer       NOT NULL,
    CONSTRAINT "UQ_MatchLogSets_LogIndex" UNIQUE ("MatchLogId", "SetIndex")
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_MatchLogSets_MatchLog') THEN
        ALTER TABLE "MatchLogSets" ADD CONSTRAINT "FK_MatchLogSets_MatchLog"
            FOREIGN KEY ("MatchLogId") REFERENCES "MatchLogs"("Id") ON DELETE CASCADE;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_MatchLogSets_MatchLog" ON "MatchLogSets"("MatchLogId");

COMMIT;
