-- =============================================================================
-- pg_init.sql  (PostgreSQL 17)
-- VolleyballTrainingTracker schema —— 合併版 DDL，反映 EF Core 實體最終狀態
-- （PascalCase 識別字，Npgsql 預設加引號）。
--
-- 使用方式（資料庫已先建好 VOLLEYBALLTRAININGTRACKER）：
--   psql -U postgres -d VOLLEYBALLTRAININGTRACKER -f pg_init.sql
--
-- 只建結構，不含資料。重複執行安全（全部 IF NOT EXISTS / DROP ... IF EXISTS）。
-- =============================================================================

BEGIN;

-- ---------- Roles ----------
CREATE TABLE IF NOT EXISTS "Roles" (
    "Id"              integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"            varchar(32)   NOT NULL,
    "Description"     varchar(256)  NULL,
    "AllowedPages"    text          NOT NULL DEFAULT '[]',
    "Permissions"     text          NOT NULL DEFAULT '[]',
    "IsSystem"        boolean       NOT NULL DEFAULT false,
    "CreatedAt"       timestamptz   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt"       timestamptz   NULL,
    "CreatedByUserId" integer       NULL,
    "UpdatedByUserId" integer       NULL
);

-- ---------- Users ----------
CREATE TABLE IF NOT EXISTS "Users" (
    "Id"              integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserName"        varchar(64)   NOT NULL,
    "Email"           varchar(256)  NOT NULL,
    "PasswordHash"    varchar(256)  NOT NULL,
    "RoleId"          integer       NOT NULL,
    "DisplayName"     varchar(64)   NULL,
    "IsActive"        boolean       NOT NULL DEFAULT true,
    "CreatedAt"       timestamptz   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt"       timestamptz   NULL,
    "CreatedByUserId" integer       NULL,
    "UpdatedByUserId" integer       NULL,
    "LastLoginAt"     timestamptz   NULL                          -- 最近一次成功登入時間（UTC），未登入過為 NULL
);

-- ---------- Players ----------
CREATE TABLE IF NOT EXISTS "Players" (
    "Id"              integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"          integer       NULL,
    "StudentId"       varchar(32)   NULL,                      -- 學號（唯一，可空；多用於對應校內學號）
    "Name"            varchar(64)   NOT NULL,
    "Nickname"        varchar(32)   NULL,
    "JerseyNo"        integer       NULL,
    "Position"        varchar(64)   NULL,                      -- 多選逗號分隔，如 OH,MB
    "HeightCm"        integer       NULL,
    "WeightKg"        integer       NULL,
    "DominantHand"    varchar(8)    NULL,
    "BirthDate"       date          NULL,
    "JoinedAt"        date          NOT NULL DEFAULT current_date,
    "Grade"           integer       NULL,
    "IsActive"        smallint      NOT NULL DEFAULT 1,        -- 1=現役 / 0=畢業 / 2=離隊
    "MemberType"      smallint      NOT NULL DEFAULT 0,        -- 0=選手 / 1=教練 / 2=球經
    "Notes"           varchar(512)  NULL,
    "CreatedAt"       timestamptz   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt"       timestamptz   NULL,
    "CreatedByUserId" integer       NULL,
    "UpdatedByUserId" integer       NULL,
    CONSTRAINT "CK_Players_DominantHand" CHECK ("DominantHand" IS NULL OR "DominantHand" IN ('Left', 'Right')),
    CONSTRAINT "CK_Players_IsActive"     CHECK ("IsActive" IN (0, 1, 2)),
    CONSTRAINT "CK_Players_MemberType"   CHECK ("MemberType" IN (0, 1, 2))
);

-- 升級用：舊資料庫尚未新增 MemberType 欄位時補上（idempotent）
ALTER TABLE "Players"
    ADD COLUMN IF NOT EXISTS "MemberType" smallint NOT NULL DEFAULT 0;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'CK_Players_MemberType'
           AND conrelid = '"Players"'::regclass
    ) THEN
        ALTER TABLE "Players"
            ADD CONSTRAINT "CK_Players_MemberType" CHECK ("MemberType" IN (0, 1, 2));
    END IF;
END$$;

CREATE INDEX IF NOT EXISTS "IX_Players_MemberType" ON "Players"("MemberType");

-- ---------- Drills ----------
CREATE TABLE IF NOT EXISTS "Drills" (
    "Id"              integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"            varchar(64)   NOT NULL,
    "Category"        varchar(32)   NOT NULL,
    "Description"     varchar(512)  NULL,
    "IsActive"        boolean       NOT NULL DEFAULT true,
    "CreatedAt"       timestamptz   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt"       timestamptz   NULL,
    "CreatedByUserId" integer       NULL,
    "UpdatedByUserId" integer       NULL,
    CONSTRAINT "CK_Drills_Category" CHECK ("Category" IN ('Basic','Serve','Pass','Set','Attack','Block','Dig','Fitness'))
);

-- ---------- TrainingSessions ----------
CREATE TABLE IF NOT EXISTS "TrainingSessions" (
    "Id"              integer        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SessionDate"     date           NOT NULL,
    "StartTime"       time(0)        NULL,
    "DurationMin"     integer        NULL,
    "Location"        varchar(128)   NULL,
    "Theme"           varchar(128)   NULL,
    "CoachUserId"     integer        NOT NULL,
    "Notes"           varchar(1024)  NULL,
    "CreatedAt"       timestamptz    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt"       timestamptz    NULL,
    "CreatedByUserId" integer        NULL,
    "UpdatedByUserId" integer        NULL
);

-- ---------- SessionDrills (Session <-> Drill 多對多) ----------
CREATE TABLE IF NOT EXISTS "SessionDrills" (
    "SessionId"       integer       NOT NULL,
    "DrillId"         integer       NOT NULL,
    "CreatedAt"       timestamptz   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "CreatedByUserId" integer       NULL,
    CONSTRAINT "PK_SessionDrills" PRIMARY KEY ("SessionId", "DrillId")
);

-- ---------- MatchEvents ----------
CREATE TABLE IF NOT EXISTS "MatchEvents" (
    "Id"              integer        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MatchDate"       date           NOT NULL,
    "MatchType"       varchar(16)    NULL,                      -- Official / Friendly
    "AcademicYear"    integer        NULL,
    "MatchName"       varchar(128)   NULL,
    "Location"        varchar(128)   NULL,
    "Ranking"         varchar(64)    NULL,
    "RankingB"        varchar(64)    NULL,
    "VideoUrl"        varchar(512)   NULL,
    "Notes"           varchar(1024)  NULL,
    "SquadCount"      integer        NOT NULL DEFAULT 1,
    "CreatedAt"       timestamptz    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt"       timestamptz    NULL,
    "CreatedByUserId" integer        NULL,
    "UpdatedByUserId" integer        NULL
);

-- ---------- MatchEventPlayers (出賽名單 M:N + snapshot) ----------
CREATE TABLE IF NOT EXISTS "MatchEventPlayers" (
    "MatchEventId"    integer       NOT NULL,
    "PlayerId"        integer       NOT NULL,
    "CreatedAt"       timestamptz   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "OurSquad"        varchar(16)   NULL,
    "PlayerName"      varchar(64)   NOT NULL,
    "JerseyNo"        integer       NULL,
    "Position"        varchar(64)   NULL,
    CONSTRAINT "PK_MatchEventPlayers" PRIMARY KEY ("MatchEventId", "PlayerId")
);

-- ---------- MatchLogs (每筆對戰) ----------
CREATE TABLE IF NOT EXISTS "MatchLogs" (
    "Id"              integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MatchEventId"    integer       NOT NULL,
    "Opponent"        varchar(128)  NOT NULL,
    "OurSquad"        varchar(16)   NULL,
    "Set1Our"         integer       NULL,
    "Set1Opp"         integer       NULL,
    "Set2Our"         integer       NULL,
    "Set2Opp"         integer       NULL,
    "Set3Our"         integer       NULL,
    "Set3Opp"         integer       NULL,
    "OurScore"        integer       NULL,
    "OpponentScore"   integer       NULL,
    "Result"          varchar(8)    NULL,
    "MatchDate"       date          NULL,
    "CreatedAt"       timestamptz   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt"       timestamptz   NULL,
    "CreatedByUserId" integer       NULL,
    "UpdatedByUserId" integer       NULL,
    CONSTRAINT "CK_MatchLogs_Result" CHECK ("Result" IS NULL OR "Result" IN ('W','L','D'))
);

-- ---------- MatchLogSets (友誼賽動態局分子表) ----------
-- 僅在 MatchEvent.MatchType=Friendly 時寫入；Official 賽事一律不寫入。
CREATE TABLE IF NOT EXISTS "MatchLogSets" (
    "Id"              integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MatchLogId"      integer       NOT NULL,
    "SetIndex"        smallint      NOT NULL,
    "OurScore"        integer       NOT NULL,
    "OpponentScore"   integer       NOT NULL,
    CONSTRAINT "UQ_MatchLogSets_LogIndex" UNIQUE ("MatchLogId", "SetIndex")
);

-- ---------- CryingLogs (哭哭榜) ----------
CREATE TABLE IF NOT EXISTS "CryingLogs" (
    "Id"              integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OccurredAt"      date          NOT NULL DEFAULT current_date,
    "CrierPlayerId"   integer       NOT NULL,
    "Reason"          varchar(256)  NOT NULL,
    "Notes"           varchar(1024) NULL,
    "CreatedAt"       timestamptz   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt"       timestamptz   NULL,
    "CreatedByUserId" integer       NULL,
    "UpdatedByUserId" integer       NULL
);

-- ---------- CryingLogCulprits (一筆哭哭事件對應多位「加分者」；可為球員或外部名字) ----------
-- PlayerId 與 ExternalName 二擇一（CHECK 強制），同事件不允許同球員或同外部名重複（partial unique）。
CREATE TABLE IF NOT EXISTS "CryingLogCulprits" (
    "Id"           integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CryingLogId"  integer       NOT NULL,
    "PlayerId"     integer       NULL,
    "ExternalName" varchar(64)   NULL,
    CONSTRAINT "CK_CryingLogCulprits_OneOf" CHECK (
        ("PlayerId" IS NOT NULL AND "ExternalName" IS NULL) OR
        ("PlayerId" IS NULL AND "ExternalName" IS NOT NULL)
    )
);

-- ---------- BoardPosts (留言板貼文，純文字) ----------
CREATE TABLE IF NOT EXISTS "BoardPosts" (
    "Id"              integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Content"         varchar(2000) NOT NULL,
    "IsPinned"        boolean       NOT NULL DEFAULT false,
    "IsDeleted"       boolean       NOT NULL DEFAULT false,    -- 軟刪除
    "CreatedAt"       timestamptz   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt"       timestamptz   NULL,
    "CreatedByUserId" integer       NULL,                      -- ＝作者
    "UpdatedByUserId" integer       NULL
);

-- ---------- BoardComments (回覆，單層) ----------
CREATE TABLE IF NOT EXISTS "BoardComments" (
    "Id"              integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PostId"          integer       NOT NULL,
    "Content"         varchar(1000) NOT NULL,
    "IsDeleted"       boolean       NOT NULL DEFAULT false,
    "CreatedAt"       timestamptz   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt"       timestamptz   NULL,
    "CreatedByUserId" integer       NULL,
    "UpdatedByUserId" integer       NULL
);

-- ---------- BoardReactions (貼文層級按讚/表情) ----------
-- 每位使用者對同一貼文的同一 Emoji 僅一筆（UX 唯一索引強制）。
CREATE TABLE IF NOT EXISTS "BoardReactions" (
    "Id"        integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PostId"    integer     NOT NULL,
    "UserId"    integer     NOT NULL,
    "Emoji"     varchar(16) NOT NULL DEFAULT '❤',
    "CreatedAt" timestamptz NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

-- ---------- AuditDeletes (刪除稽核) ----------
CREATE TABLE IF NOT EXISTS "AuditDeletes" (
    "Id"              bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TableName"       varchar(64)   NOT NULL,
    "RowId"           integer       NOT NULL,
    "DeletedByUserId" integer       NULL,
    "DeletedAt"       timestamptz   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "RowJson"         text          NULL
);

-- ---------- Sponsors (隊費贊助者名冊；可連結人員或為陣容外人士) ----------
-- PlayerId 連結現役/畢業/離隊人員；外部人士（學長姊/家長/廠商）留空，名稱填於 DisplayName。
-- Identity：0=學姊 1=學長 2=家長 3=廠商 4=其他。
CREATE TABLE IF NOT EXISTS "Sponsors" (
    "Id"              integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PlayerId"        integer       NULL,
    "DisplayName"     varchar(64)   NOT NULL,
    "Identity"        smallint      NOT NULL DEFAULT 4,
    "Notes"           varchar(256)  NULL,
    "CreatedAt"       timestamptz   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt"       timestamptz   NULL,
    "CreatedByUserId" integer       NULL,
    "UpdatedByUserId" integer       NULL,
    CONSTRAINT "CK_Sponsors_Identity" CHECK ("Identity" BETWEEN 0 AND 4)
);

-- ---------- Sponsorships (隊費贊助紀錄；連結贊助者名冊，金額單位為元) ----------
CREATE TABLE IF NOT EXISTS "Sponsorships" (
    "Id"              integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SponsorId"       integer       NOT NULL,
    "Amount"          integer       NOT NULL,
    "OccurredAt"      date          NOT NULL DEFAULT current_date,
    "Purpose"         varchar(128)  NULL,
    "Notes"           varchar(256)  NULL,
    "CreatedAt"       timestamptz   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt"       timestamptz   NULL,
    "CreatedByUserId" integer       NULL,
    "UpdatedByUserId" integer       NULL,
    CONSTRAINT "CK_Sponsorships_AmountPositive" CHECK ("Amount" > 0)
);

-- =============================================================================
-- 外鍵（全部資料表建立後再加，避免 Roles <-> Users 互相參照的順序問題）
-- =============================================================================
DO $$
BEGIN
    -- Roles
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Roles_CreatedBy') THEN
        ALTER TABLE "Roles" ADD CONSTRAINT "FK_Roles_CreatedBy"
            FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Roles_UpdatedBy') THEN
        ALTER TABLE "Roles" ADD CONSTRAINT "FK_Roles_UpdatedBy"
            FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users"("Id");
    END IF;

    -- Users
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Users_Roles_RoleId') THEN
        ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_Roles_RoleId"
            FOREIGN KEY ("RoleId") REFERENCES "Roles"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Users_CreatedBy') THEN
        ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_CreatedBy"
            FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Users_UpdatedBy') THEN
        ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_UpdatedBy"
            FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users"("Id");
    END IF;

    -- Players
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Players_Users') THEN
        ALTER TABLE "Players" ADD CONSTRAINT "FK_Players_Users"
            FOREIGN KEY ("UserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Players_CreatedBy') THEN
        ALTER TABLE "Players" ADD CONSTRAINT "FK_Players_CreatedBy"
            FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Players_UpdatedBy') THEN
        ALTER TABLE "Players" ADD CONSTRAINT "FK_Players_UpdatedBy"
            FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users"("Id");
    END IF;

    -- Drills
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Drills_CreatedBy') THEN
        ALTER TABLE "Drills" ADD CONSTRAINT "FK_Drills_CreatedBy"
            FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Drills_UpdatedBy') THEN
        ALTER TABLE "Drills" ADD CONSTRAINT "FK_Drills_UpdatedBy"
            FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users"("Id");
    END IF;

    -- TrainingSessions
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_TrainingSessions_Users') THEN
        ALTER TABLE "TrainingSessions" ADD CONSTRAINT "FK_TrainingSessions_Users"
            FOREIGN KEY ("CoachUserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_TrainingSessions_CreatedBy') THEN
        ALTER TABLE "TrainingSessions" ADD CONSTRAINT "FK_TrainingSessions_CreatedBy"
            FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_TrainingSessions_UpdatedBy') THEN
        ALTER TABLE "TrainingSessions" ADD CONSTRAINT "FK_TrainingSessions_UpdatedBy"
            FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users"("Id");
    END IF;

    -- SessionDrills
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_SessionDrills_Session') THEN
        ALTER TABLE "SessionDrills" ADD CONSTRAINT "FK_SessionDrills_Session"
            FOREIGN KEY ("SessionId") REFERENCES "TrainingSessions"("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_SessionDrills_Drill') THEN
        ALTER TABLE "SessionDrills" ADD CONSTRAINT "FK_SessionDrills_Drill"
            FOREIGN KEY ("DrillId") REFERENCES "Drills"("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_SessionDrills_CreatedBy') THEN
        ALTER TABLE "SessionDrills" ADD CONSTRAINT "FK_SessionDrills_CreatedBy"
            FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id");
    END IF;

    -- MatchEvents
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_MatchEvents_CreatedBy') THEN
        ALTER TABLE "MatchEvents" ADD CONSTRAINT "FK_MatchEvents_CreatedBy"
            FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_MatchEvents_UpdatedBy') THEN
        ALTER TABLE "MatchEvents" ADD CONSTRAINT "FK_MatchEvents_UpdatedBy"
            FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users"("Id");
    END IF;

    -- MatchEventPlayers
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_MatchEventPlayers_Event') THEN
        ALTER TABLE "MatchEventPlayers" ADD CONSTRAINT "FK_MatchEventPlayers_Event"
            FOREIGN KEY ("MatchEventId") REFERENCES "MatchEvents"("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_MatchEventPlayers_Player') THEN
        ALTER TABLE "MatchEventPlayers" ADD CONSTRAINT "FK_MatchEventPlayers_Player"
            FOREIGN KEY ("PlayerId") REFERENCES "Players"("Id") ON DELETE CASCADE;
    END IF;

    -- MatchLogs
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_MatchLogs_Event') THEN
        ALTER TABLE "MatchLogs" ADD CONSTRAINT "FK_MatchLogs_Event"
            FOREIGN KEY ("MatchEventId") REFERENCES "MatchEvents"("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_MatchLogs_CreatedBy') THEN
        ALTER TABLE "MatchLogs" ADD CONSTRAINT "FK_MatchLogs_CreatedBy"
            FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_MatchLogs_UpdatedBy') THEN
        ALTER TABLE "MatchLogs" ADD CONSTRAINT "FK_MatchLogs_UpdatedBy"
            FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users"("Id");
    END IF;

    -- MatchLogSets
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_MatchLogSets_MatchLog') THEN
        ALTER TABLE "MatchLogSets" ADD CONSTRAINT "FK_MatchLogSets_MatchLog"
            FOREIGN KEY ("MatchLogId") REFERENCES "MatchLogs"("Id") ON DELETE CASCADE;
    END IF;

    -- AuditDeletes
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_AuditDeletes_User') THEN
        ALTER TABLE "AuditDeletes" ADD CONSTRAINT "FK_AuditDeletes_User"
            FOREIGN KEY ("DeletedByUserId") REFERENCES "Users"("Id") ON DELETE SET NULL;
    END IF;

    -- CryingLogs
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_CryingLogs_Crier') THEN
        ALTER TABLE "CryingLogs" ADD CONSTRAINT "FK_CryingLogs_Crier"
            FOREIGN KEY ("CrierPlayerId") REFERENCES "Players"("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_CryingLogs_CreatedBy') THEN
        ALTER TABLE "CryingLogs" ADD CONSTRAINT "FK_CryingLogs_CreatedBy"
            FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_CryingLogs_UpdatedBy') THEN
        ALTER TABLE "CryingLogs" ADD CONSTRAINT "FK_CryingLogs_UpdatedBy"
            FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users"("Id");
    END IF;

    -- CryingLogCulprits
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_CryingLogCulprits_Log') THEN
        ALTER TABLE "CryingLogCulprits" ADD CONSTRAINT "FK_CryingLogCulprits_Log"
            FOREIGN KEY ("CryingLogId") REFERENCES "CryingLogs"("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_CryingLogCulprits_Player') THEN
        ALTER TABLE "CryingLogCulprits" ADD CONSTRAINT "FK_CryingLogCulprits_Player"
            FOREIGN KEY ("PlayerId") REFERENCES "Players"("Id") ON DELETE RESTRICT;
    END IF;

    -- BoardPosts
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_BoardPosts_CreatedBy') THEN
        ALTER TABLE "BoardPosts" ADD CONSTRAINT "FK_BoardPosts_CreatedBy"
            FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_BoardPosts_UpdatedBy') THEN
        ALTER TABLE "BoardPosts" ADD CONSTRAINT "FK_BoardPosts_UpdatedBy"
            FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users"("Id");
    END IF;

    -- BoardComments
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_BoardComments_Post') THEN
        ALTER TABLE "BoardComments" ADD CONSTRAINT "FK_BoardComments_Post"
            FOREIGN KEY ("PostId") REFERENCES "BoardPosts"("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_BoardComments_CreatedBy') THEN
        ALTER TABLE "BoardComments" ADD CONSTRAINT "FK_BoardComments_CreatedBy"
            FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_BoardComments_UpdatedBy') THEN
        ALTER TABLE "BoardComments" ADD CONSTRAINT "FK_BoardComments_UpdatedBy"
            FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users"("Id");
    END IF;

    -- BoardReactions
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_BoardReactions_Post') THEN
        ALTER TABLE "BoardReactions" ADD CONSTRAINT "FK_BoardReactions_Post"
            FOREIGN KEY ("PostId") REFERENCES "BoardPosts"("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_BoardReactions_User') THEN
        ALTER TABLE "BoardReactions" ADD CONSTRAINT "FK_BoardReactions_User"
            FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE CASCADE;
    END IF;

    -- Sponsors
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Sponsors_Player') THEN
        ALTER TABLE "Sponsors" ADD CONSTRAINT "FK_Sponsors_Player"
            FOREIGN KEY ("PlayerId") REFERENCES "Players"("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Sponsors_CreatedBy') THEN
        ALTER TABLE "Sponsors" ADD CONSTRAINT "FK_Sponsors_CreatedBy"
            FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Sponsors_UpdatedBy') THEN
        ALTER TABLE "Sponsors" ADD CONSTRAINT "FK_Sponsors_UpdatedBy"
            FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users"("Id");
    END IF;

    -- Sponsorships
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Sponsorships_Sponsor') THEN
        ALTER TABLE "Sponsorships" ADD CONSTRAINT "FK_Sponsorships_Sponsor"
            FOREIGN KEY ("SponsorId") REFERENCES "Sponsors"("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Sponsorships_CreatedBy') THEN
        ALTER TABLE "Sponsorships" ADD CONSTRAINT "FK_Sponsorships_CreatedBy"
            FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Sponsorships_UpdatedBy') THEN
        ALTER TABLE "Sponsorships" ADD CONSTRAINT "FK_Sponsorships_UpdatedBy"
            FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users"("Id");
    END IF;
END $$;

-- =============================================================================
-- 索引
-- =============================================================================
CREATE UNIQUE INDEX IF NOT EXISTS "UX_Roles_Name"            ON "Roles"("Name");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_Users_UserName"        ON "Users"("UserName");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_Drills_Name"           ON "Drills"("Name");
CREATE INDEX IF NOT EXISTS "IX_Players_UserId"               ON "Players"("UserId");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_Players_StudentId"     ON "Players"("StudentId") WHERE "StudentId" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "IX_TrainingSessions_Date"        ON "TrainingSessions"("SessionDate" DESC);
CREATE INDEX IF NOT EXISTS "IX_SessionDrills_Drill"          ON "SessionDrills"("DrillId");
CREATE INDEX IF NOT EXISTS "IX_MatchEvents_Date"             ON "MatchEvents"("MatchDate" DESC);
CREATE INDEX IF NOT EXISTS "IX_MatchEventPlayers_Player"     ON "MatchEventPlayers"("PlayerId");
CREATE INDEX IF NOT EXISTS "IX_MatchLogs_Event"              ON "MatchLogs"("MatchEventId");
CREATE INDEX IF NOT EXISTS "IX_MatchLogSets_MatchLog"        ON "MatchLogSets"("MatchLogId");
CREATE INDEX IF NOT EXISTS "IX_AuditDeletes_Table_Row"       ON "AuditDeletes"("TableName", "RowId");
CREATE INDEX IF NOT EXISTS "IX_CryingLogs_OccurredAt"            ON "CryingLogs"("OccurredAt" DESC);
CREATE INDEX IF NOT EXISTS "IX_CryingLogs_Crier"                 ON "CryingLogs"("CrierPlayerId");
CREATE INDEX IF NOT EXISTS "IX_CryingLogCulprits_Log"            ON "CryingLogCulprits"("CryingLogId");
CREATE INDEX IF NOT EXISTS "IX_CryingLogCulprits_Player"         ON "CryingLogCulprits"("PlayerId") WHERE "PlayerId" IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "UX_CryingLogCulprits_LogPlayer"
    ON "CryingLogCulprits"("CryingLogId","PlayerId") WHERE "PlayerId" IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "UX_CryingLogCulprits_LogExternal"
    ON "CryingLogCulprits"("CryingLogId","ExternalName") WHERE "ExternalName" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "IX_BoardPosts_Pinned_Created"     ON "BoardPosts"("IsPinned", "CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_BoardComments_Post"            ON "BoardComments"("PostId");
CREATE INDEX IF NOT EXISTS "IX_BoardReactions_Post"           ON "BoardReactions"("PostId");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_BoardReactions_Post_User_Emoji"
    ON "BoardReactions"("PostId","UserId","Emoji");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_Sponsors_Player"        ON "Sponsors"("PlayerId") WHERE "PlayerId" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "IX_Sponsorships_Sponsor"          ON "Sponsorships"("SponsorId");
CREATE INDEX IF NOT EXISTS "IX_Sponsorships_OccurredAt"       ON "Sponsorships"("OccurredAt" DESC);

COMMIT;

-- =============================================================================
-- 若手動匯入資料，務必執行 `setval` 把各 identity 序列推進到目前最大 Id，
-- 避免後續新增列時主鍵衝突。
-- =============================================================================
