-- =============================================================================
-- pg_init.sql  (PostgreSQL 15)
-- VolleyballTrainingTracker schema —— 由 MSSQL 全部 migration 套用後的「最終狀態」
-- 合併產生。對應 EF Core 實體（PascalCase 識別字，Npgsql 預設加引號）。
--
-- 使用方式（資料庫已先建好 VOLLEYBALLTRAININGTRACKER）：
--   psql -U postgres -d VOLLEYBALLTRAININGTRACKER -f pg_init.sql
--
-- 只建結構；資料由 VolleyballTrainingTracker.DataMigration 工具搬入。
-- 重複執行安全（全部 IF NOT EXISTS / DROP ... IF EXISTS）。
-- =============================================================================

BEGIN;

-- ---------- Roles ----------
CREATE TABLE IF NOT EXISTS "Roles" (
    "Id"              integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"            varchar(32)   NOT NULL,
    "Description"     varchar(256)  NULL,
    "AllowedPages"    text          NOT NULL DEFAULT '[]',
    "Permissions"     text          NOT NULL DEFAULT '[]',
    "IsSystem"        boolean       NOT NULL DEFAULT false,
    "CreatedAt"       timestamptz   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt"       timestamptz   NULL,
    "CreatedByUserId" integer       NULL,
    "UpdatedByUserId" integer       NULL
);

-- ---------- Users ----------
CREATE TABLE IF NOT EXISTS "Users" (
    "Id"              integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserName"        varchar(64)   NOT NULL,
    "Email"           varchar(256)  NOT NULL,
    "PasswordHash"    varchar(256)  NOT NULL,
    "RoleId"          integer       NOT NULL,
    "DisplayName"     varchar(64)   NULL,
    "IsActive"        boolean       NOT NULL DEFAULT true,
    "CreatedAt"       timestamptz   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt"       timestamptz   NULL,
    "CreatedByUserId" integer       NULL,
    "UpdatedByUserId" integer       NULL
);

-- ---------- Players ----------
CREATE TABLE IF NOT EXISTS "Players" (
    "Id"              integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"          integer       NULL,
    "Name"            varchar(64)   NOT NULL,
    "Nickname"        varchar(32)   NULL,
    "JerseyNo"        integer       NULL,
    "Position"        varchar(64)   NULL,                      -- 多選逗號分隔，如 OH,MB
    "HeightCm"        integer       NULL,
    "WeightKg"        integer       NULL,
    "DominantHand"    varchar(8)    NULL,
    "BirthDate"       date          NULL,
    "JoinedAt"        date          NOT NULL DEFAULT current_date,
    "Grade"           integer       NULL,
    "IsActive"        smallint      NOT NULL DEFAULT 1,        -- 1=現役 / 0=畢業 / 2=退隊
    "Notes"           varchar(512)  NULL,
    "CreatedAt"       timestamptz   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt"       timestamptz   NULL,
    "CreatedByUserId" integer       NULL,
    "UpdatedByUserId" integer       NULL,
    CONSTRAINT "CK_Players_DominantHand" CHECK ("DominantHand" IS NULL OR "DominantHand" IN ('Left', 'Right')),
    CONSTRAINT "CK_Players_IsActive"     CHECK ("IsActive" IN (0, 1, 2))
);

-- ---------- Drills ----------
CREATE TABLE IF NOT EXISTS "Drills" (
    "Id"              integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"            varchar(64)   NOT NULL,
    "Category"        varchar(32)   NOT NULL,
    "Description"     varchar(512)  NULL,
    "IsActive"        boolean       NOT NULL DEFAULT true,
    "CreatedAt"       timestamptz   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt"       timestamptz   NULL,
    "CreatedByUserId" integer       NULL,
    "UpdatedByUserId" integer       NULL,
    CONSTRAINT "CK_Drills_Category" CHECK ("Category" IN ('Basic','Serve','Pass','Set','Attack','Block','Dig','Fitness'))
);

-- ---------- TrainingSessions ----------
CREATE TABLE IF NOT EXISTS "TrainingSessions" (
    "Id"              integer        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SessionDate"     date           NOT NULL,
    "StartTime"       time(0)        NULL,
    "DurationMin"     integer        NULL,
    "Location"        varchar(128)   NULL,
    "Theme"           varchar(128)   NULL,
    "CoachUserId"     integer        NOT NULL,
    "Notes"           varchar(1024)  NULL,
    "CreatedAt"       timestamptz    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt"       timestamptz    NULL,
    "CreatedByUserId" integer        NULL,
    "UpdatedByUserId" integer        NULL
);

-- ---------- SessionDrills (Session <-> Drill 多對多) ----------
CREATE TABLE IF NOT EXISTS "SessionDrills" (
    "SessionId"       integer       NOT NULL,
    "DrillId"         integer       NOT NULL,
    "CreatedAt"       timestamptz   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "CreatedByUserId" integer       NULL,
    CONSTRAINT "PK_SessionDrills" PRIMARY KEY ("SessionId", "DrillId")
);

-- ---------- MatchEvents ----------
CREATE TABLE IF NOT EXISTS "MatchEvents" (
    "Id"              integer        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MatchDate"       date           NOT NULL,
    "MatchType"       varchar(16)    NULL,                      -- Official / Friendly
    "AcademicYear"    integer        NULL,
    "MatchName"       varchar(128)   NULL,
    "Location"        varchar(128)   NULL,
    "Ranking"         varchar(64)    NULL,
    "RankingB"        varchar(64)    NULL,
    "VideoUrl"        varchar(512)   NULL,
    "Notes"           varchar(1024)  NULL,
    "SquadCount"      integer        NOT NULL DEFAULT 1,
    "CreatedAt"       timestamptz    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt"       timestamptz    NULL,
    "CreatedByUserId" integer        NULL,
    "UpdatedByUserId" integer        NULL
);

-- ---------- MatchEventPlayers (出賽名單 M:N + snapshot) ----------
CREATE TABLE IF NOT EXISTS "MatchEventPlayers" (
    "MatchEventId"    integer       NOT NULL,
    "PlayerId"        integer       NOT NULL,
    "CreatedAt"       timestamptz   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "OurSquad"        varchar(16)   NULL,
    "PlayerName"      varchar(64)   NOT NULL,
    "JerseyNo"        integer       NULL,
    "Position"        varchar(64)   NULL,
    CONSTRAINT "PK_MatchEventPlayers" PRIMARY KEY ("MatchEventId", "PlayerId")
);

-- ---------- MatchLogs (每筆對戰) ----------
CREATE TABLE IF NOT EXISTS "MatchLogs" (
    "Id"              integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MatchEventId"    integer       NOT NULL,
    "Opponent"        varchar(128)  NOT NULL,
    "OurSquad"        varchar(16)   NULL,
    "Set1Our"         integer       NULL,
    "Set1Opp"         integer       NULL,
    "Set2Our"         integer       NULL,
    "Set2Opp"         integer       NULL,
    "Set3Our"         integer       NULL,
    "Set3Opp"         integer       NULL,
    "OurScore"        integer       NULL,
    "OpponentScore"   integer       NULL,
    "Result"          varchar(8)    NULL,
    "CreatedAt"       timestamptz   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt"       timestamptz   NULL,
    "CreatedByUserId" integer       NULL,
    "UpdatedByUserId" integer       NULL,
    CONSTRAINT "CK_MatchLogs_Result" CHECK ("Result" IS NULL OR "Result" IN ('W','L','D'))
);

-- ---------- AuditDeletes (刪除稽核) ----------
CREATE TABLE IF NOT EXISTS "AuditDeletes" (
    "Id"              bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TableName"       varchar(64)   NOT NULL,
    "RowId"           integer       NOT NULL,
    "DeletedByUserId" integer       NULL,
    "DeletedAt"       timestamptz   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "RowJson"         text          NULL
);

-- =============================================================================
-- 外鍵（全部資料表建立後再加，避免 Roles <-> Users 互相參照的順序問題）
-- =============================================================================
DO $$
BEGIN
    -- Roles
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Roles_CreatedBy') THEN
        ALTER TABLE "Roles" ADD CONSTRAINT "FK_Roles_CreatedBy"
            FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Roles_UpdatedBy') THEN
        ALTER TABLE "Roles" ADD CONSTRAINT "FK_Roles_UpdatedBy"
            FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users"("Id");
    END IF;

    -- Users
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Users_Roles_RoleId') THEN
        ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_Roles_RoleId"
            FOREIGN KEY ("RoleId") REFERENCES "Roles"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Users_CreatedBy') THEN
        ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_CreatedBy"
            FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Users_UpdatedBy') THEN
        ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_UpdatedBy"
            FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users"("Id");
    END IF;

    -- Players
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Players_Users') THEN
        ALTER TABLE "Players" ADD CONSTRAINT "FK_Players_Users"
            FOREIGN KEY ("UserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Players_CreatedBy') THEN
        ALTER TABLE "Players" ADD CONSTRAINT "FK_Players_CreatedBy"
            FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Players_UpdatedBy') THEN
        ALTER TABLE "Players" ADD CONSTRAINT "FK_Players_UpdatedBy"
            FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users"("Id");
    END IF;

    -- Drills
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Drills_CreatedBy') THEN
        ALTER TABLE "Drills" ADD CONSTRAINT "FK_Drills_CreatedBy"
            FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Drills_UpdatedBy') THEN
        ALTER TABLE "Drills" ADD CONSTRAINT "FK_Drills_UpdatedBy"
            FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users"("Id");
    END IF;

    -- TrainingSessions
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_TrainingSessions_Users') THEN
        ALTER TABLE "TrainingSessions" ADD CONSTRAINT "FK_TrainingSessions_Users"
            FOREIGN KEY ("CoachUserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_TrainingSessions_CreatedBy') THEN
        ALTER TABLE "TrainingSessions" ADD CONSTRAINT "FK_TrainingSessions_CreatedBy"
            FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_TrainingSessions_UpdatedBy') THEN
        ALTER TABLE "TrainingSessions" ADD CONSTRAINT "FK_TrainingSessions_UpdatedBy"
            FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users"("Id");
    END IF;

    -- SessionDrills
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_SessionDrills_Session') THEN
        ALTER TABLE "SessionDrills" ADD CONSTRAINT "FK_SessionDrills_Session"
            FOREIGN KEY ("SessionId") REFERENCES "TrainingSessions"("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_SessionDrills_Drill') THEN
        ALTER TABLE "SessionDrills" ADD CONSTRAINT "FK_SessionDrills_Drill"
            FOREIGN KEY ("DrillId") REFERENCES "Drills"("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_SessionDrills_CreatedBy') THEN
        ALTER TABLE "SessionDrills" ADD CONSTRAINT "FK_SessionDrills_CreatedBy"
            FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id");
    END IF;

    -- MatchEvents
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_MatchEvents_CreatedBy') THEN
        ALTER TABLE "MatchEvents" ADD CONSTRAINT "FK_MatchEvents_CreatedBy"
            FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_MatchEvents_UpdatedBy') THEN
        ALTER TABLE "MatchEvents" ADD CONSTRAINT "FK_MatchEvents_UpdatedBy"
            FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users"("Id");
    END IF;

    -- MatchEventPlayers
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_MatchEventPlayers_Event') THEN
        ALTER TABLE "MatchEventPlayers" ADD CONSTRAINT "FK_MatchEventPlayers_Event"
            FOREIGN KEY ("MatchEventId") REFERENCES "MatchEvents"("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_MatchEventPlayers_Player') THEN
        ALTER TABLE "MatchEventPlayers" ADD CONSTRAINT "FK_MatchEventPlayers_Player"
            FOREIGN KEY ("PlayerId") REFERENCES "Players"("Id") ON DELETE CASCADE;
    END IF;

    -- MatchLogs
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_MatchLogs_Event') THEN
        ALTER TABLE "MatchLogs" ADD CONSTRAINT "FK_MatchLogs_Event"
            FOREIGN KEY ("MatchEventId") REFERENCES "MatchEvents"("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_MatchLogs_CreatedBy') THEN
        ALTER TABLE "MatchLogs" ADD CONSTRAINT "FK_MatchLogs_CreatedBy"
            FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_MatchLogs_UpdatedBy') THEN
        ALTER TABLE "MatchLogs" ADD CONSTRAINT "FK_MatchLogs_UpdatedBy"
            FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users"("Id");
    END IF;

    -- AuditDeletes
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_AuditDeletes_User') THEN
        ALTER TABLE "AuditDeletes" ADD CONSTRAINT "FK_AuditDeletes_User"
            FOREIGN KEY ("DeletedByUserId") REFERENCES "Users"("Id") ON DELETE SET NULL;
    END IF;
END $$;

-- =============================================================================
-- 索引
-- =============================================================================
CREATE UNIQUE INDEX IF NOT EXISTS "UX_Roles_Name"            ON "Roles"("Name");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_Users_UserName"        ON "Users"("UserName");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_Drills_Name"           ON "Drills"("Name");
CREATE INDEX IF NOT EXISTS "IX_Players_UserId"               ON "Players"("UserId");
CREATE INDEX IF NOT EXISTS "IX_TrainingSessions_Date"        ON "TrainingSessions"("SessionDate" DESC);
CREATE INDEX IF NOT EXISTS "IX_SessionDrills_Drill"          ON "SessionDrills"("DrillId");
CREATE INDEX IF NOT EXISTS "IX_MatchEvents_Date"             ON "MatchEvents"("MatchDate" DESC);
CREATE INDEX IF NOT EXISTS "IX_MatchEventPlayers_Player"     ON "MatchEventPlayers"("PlayerId");
CREATE INDEX IF NOT EXISTS "IX_MatchLogs_Event"              ON "MatchLogs"("MatchEventId");
CREATE INDEX IF NOT EXISTS "IX_AuditDeletes_Table_Row"       ON "AuditDeletes"("TableName", "RowId");

COMMIT;

-- =============================================================================
-- 資料搬入後務必執行：把 identity 序列推進到目前最大 Id（見 DataMigration 工具，
-- 工具會自動執行；若手動匯資料則需另外跑 setval）。
-- =============================================================================
