// AUTO-GENERATED by SchemaExporter. DO NOT EDIT.
// IDENTITY columns for [dbo].[Drills]

export const Drills_IDENTITY = {
  table: 'Drills',
  columns: [
    { name: 'Id', dataType: 'int' },
  ],
} as const;

