// AUTO-GENERATED by SchemaExporter. DO NOT EDIT.
// IDENTITY columns for [dbo].[MatchLogs]

export const MatchLogs_IDENTITY = {
  table: 'MatchLogs',
  columns: [
    { name: 'Id', dataType: 'int' },
  ],
} as const;

