// AUTO-GENERATED by SchemaExporter. DO NOT EDIT.
// IDENTITY columns for [dbo].[Players]

export const Players_IDENTITY = {
  table: 'Players',
  columns: [
    { name: 'Id', dataType: 'int' },
  ],
} as const;

