// AUTO-GENERATED by SchemaExporter. DO NOT EDIT.
// IDENTITY columns for [dbo].[TrainingSessions]

export const TrainingSessions_IDENTITY = {
  table: 'TrainingSessions',
  columns: [
    { name: 'Id', dataType: 'int' },
  ],
} as const;

