// AUTO-GENERATED by SchemaExporter. DO NOT EDIT.
// IDENTITY columns for [dbo].[Users]

export const Users_IDENTITY = {
  table: 'Users',
  columns: [
    { name: 'Id', dataType: 'int' },
  ],
} as const;

