// AUTO-GENERATED by SchemaExporter. DO NOT EDIT.
// Table: [dbo].[Drills]

export interface Drills {
  Id: number;
  Name: string;
  Category: string;
  Description: string | null;
  IsActive: boolean;
  CreatedAt: string;
}

export const Drills_META = {
  schema: 'dbo',
  name: 'Drills',
  primaryKey: ['Id'] as const,
  columns: [
    { name: 'Id', dataType: 'int', tsType: 'number', isNullable: false, isIdentity: true, maxLength: null, precision: 10, scale: 0, default: null },
    { name: 'Name', dataType: 'nvarchar', tsType: 'string', isNullable: false, isIdentity: false, maxLength: 64, precision: null, scale: null, default: null },
    { name: 'Category', dataType: 'nvarchar', tsType: 'string', isNullable: false, isIdentity: false, maxLength: 32, precision: null, scale: null, default: null },
    { name: 'Description', dataType: 'nvarchar', tsType: 'string', isNullable: true, isIdentity: false, maxLength: 512, precision: null, scale: null, default: null },
    { name: 'IsActive', dataType: 'bit', tsType: 'boolean', isNullable: false, isIdentity: false, maxLength: null, precision: null, scale: null, default: '((1))' },
    { name: 'CreatedAt', dataType: 'datetime2', tsType: 'string', isNullable: false, isIdentity: false, maxLength: null, precision: null, scale: null, default: '(sysutcdatetime())' },
  ],
  foreignKeys: [
  ],
} as const;

