// AUTO-GENERATED by SchemaExporter. DO NOT EDIT.
// Table: [dbo].[MatchLogs]

export interface MatchLogs {
  Id: number;
  MatchDate: string;
  Opponent: string;
  OurScore: number | null;
  OpponentScore: number | null;
  Result: string | null;
  Location: string | null;
  Notes: string | null;
  CreatedAt: string;
}

export const MatchLogs_META = {
  schema: 'dbo',
  name: 'MatchLogs',
  primaryKey: ['Id'] as const,
  columns: [
    { name: 'Id', dataType: 'int', tsType: 'number', isNullable: false, isIdentity: true, maxLength: null, precision: 10, scale: 0, default: null },
    { name: 'MatchDate', dataType: 'date', tsType: 'string', isNullable: false, isIdentity: false, maxLength: null, precision: null, scale: null, default: null },
    { name: 'Opponent', dataType: 'nvarchar', tsType: 'string', isNullable: false, isIdentity: false, maxLength: 128, precision: null, scale: null, default: null },
    { name: 'OurScore', dataType: 'int', tsType: 'number', isNullable: true, isIdentity: false, maxLength: null, precision: 10, scale: 0, default: null },
    { name: 'OpponentScore', dataType: 'int', tsType: 'number', isNullable: true, isIdentity: false, maxLength: null, precision: 10, scale: 0, default: null },
    { name: 'Result', dataType: 'nvarchar', tsType: 'string', isNullable: true, isIdentity: false, maxLength: 8, precision: null, scale: null, default: null },
    { name: 'Location', dataType: 'nvarchar', tsType: 'string', isNullable: true, isIdentity: false, maxLength: 128, precision: null, scale: null, default: null },
    { name: 'Notes', dataType: 'nvarchar', tsType: 'string', isNullable: true, isIdentity: false, maxLength: 1024, precision: null, scale: null, default: null },
    { name: 'CreatedAt', dataType: 'datetime2', tsType: 'string', isNullable: false, isIdentity: false, maxLength: null, precision: null, scale: null, default: '(sysutcdatetime())' },
  ],
  foreignKeys: [
  ],
} as const;

