// AUTO-GENERATED by SchemaExporter. DO NOT EDIT.
// Table: [dbo].[Players]

export interface Players {
  Id: number;
  UserId: number | null;
  Name: string;
  JerseyNo: number | null;
  Position: string | null;
  HeightCm: number | null;
  WeightKg: number | null;
  DominantHand: string | null;
  BirthDate: string | null;
  JoinedAt: string;
  IsActive: boolean;
  Notes: string | null;
  CreatedAt: string;
  UpdatedAt: string | null;
}

export const Players_META = {
  schema: 'dbo',
  name: 'Players',
  primaryKey: ['Id'] as const,
  columns: [
    { name: 'Id', dataType: 'int', tsType: 'number', isNullable: false, isIdentity: true, maxLength: null, precision: 10, scale: 0, default: null },
    { name: 'UserId', dataType: 'int', tsType: 'number', isNullable: true, isIdentity: false, maxLength: null, precision: 10, scale: 0, default: null },
    { name: 'Name', dataType: 'nvarchar', tsType: 'string', isNullable: false, isIdentity: false, maxLength: 64, precision: null, scale: null, default: null },
    { name: 'JerseyNo', dataType: 'int', tsType: 'number', isNullable: true, isIdentity: false, maxLength: null, precision: 10, scale: 0, default: null },
    { name: 'Position', dataType: 'nvarchar', tsType: 'string', isNullable: true, isIdentity: false, maxLength: 16, precision: null, scale: null, default: null },
    { name: 'HeightCm', dataType: 'int', tsType: 'number', isNullable: true, isIdentity: false, maxLength: null, precision: 10, scale: 0, default: null },
    { name: 'WeightKg', dataType: 'int', tsType: 'number', isNullable: true, isIdentity: false, maxLength: null, precision: 10, scale: 0, default: null },
    { name: 'DominantHand', dataType: 'nvarchar', tsType: 'string', isNullable: true, isIdentity: false, maxLength: 8, precision: null, scale: null, default: null },
    { name: 'BirthDate', dataType: 'date', tsType: 'string', isNullable: true, isIdentity: false, maxLength: null, precision: null, scale: null, default: null },
    { name: 'JoinedAt', dataType: 'date', tsType: 'string', isNullable: false, isIdentity: false, maxLength: null, precision: null, scale: null, default: '(CONVERT([date],sysutcdatetime()))' },
    { name: 'IsActive', dataType: 'bit', tsType: 'boolean', isNullable: false, isIdentity: false, maxLength: null, precision: null, scale: null, default: '((1))' },
    { name: 'Notes', dataType: 'nvarchar', tsType: 'string', isNullable: true, isIdentity: false, maxLength: 512, precision: null, scale: null, default: null },
    { name: 'CreatedAt', dataType: 'datetime2', tsType: 'string', isNullable: false, isIdentity: false, maxLength: null, precision: null, scale: null, default: '(sysutcdatetime())' },
    { name: 'UpdatedAt', dataType: 'datetime2', tsType: 'string', isNullable: true, isIdentity: false, maxLength: null, precision: null, scale: null, default: null },
  ],
  foreignKeys: [
    { name: 'FK_Players_Users', column: 'UserId', refTable: 'Users', refColumn: 'Id' },
  ],
} as const;

