// AUTO-GENERATED by SchemaExporter. DO NOT EDIT.
// Table: [dbo].[SessionDrills]

export interface SessionDrills {
  SessionId: number;
  DrillId: number;
  CreatedAt: string;
}

export const SessionDrills_META = {
  schema: 'dbo',
  name: 'SessionDrills',
  primaryKey: ['SessionId', 'DrillId'] as const,
  columns: [
    { name: 'SessionId', dataType: 'int', tsType: 'number', isNullable: false, isIdentity: false, maxLength: null, precision: 10, scale: 0, default: null },
    { name: 'DrillId', dataType: 'int', tsType: 'number', isNullable: false, isIdentity: false, maxLength: null, precision: 10, scale: 0, default: null },
    { name: 'CreatedAt', dataType: 'datetime2', tsType: 'string', isNullable: false, isIdentity: false, maxLength: null, precision: null, scale: null, default: '(sysutcdatetime())' },
  ],
  foreignKeys: [
    { name: 'FK_SessionDrills_Drill', column: 'DrillId', refTable: 'Drills', refColumn: 'Id' },
    { name: 'FK_SessionDrills_Session', column: 'SessionId', refTable: 'TrainingSessions', refColumn: 'Id' },
  ],
} as const;
