// AUTO-GENERATED by SchemaExporter. DO NOT EDIT.
// Table: [dbo].[TrainingSessions]

export interface TrainingSessions {
  Id: number;
  SessionDate: string;
  StartTime: string | null;
  DurationMin: number | null;
  Location: string | null;
  Theme: string | null;
  CoachUserId: number;
  Notes: string | null;
  CreatedAt: string;
  UpdatedAt: string | null;
}

export const TrainingSessions_META = {
  schema: 'dbo',
  name: 'TrainingSessions',
  primaryKey: ['Id'] as const,
  columns: [
    { name: 'Id', dataType: 'int', tsType: 'number', isNullable: false, isIdentity: true, maxLength: null, precision: 10, scale: 0, default: null },
    { name: 'SessionDate', dataType: 'date', tsType: 'string', isNullable: false, isIdentity: false, maxLength: null, precision: null, scale: null, default: null },
    { name: 'StartTime', dataType: 'time', tsType: 'string', isNullable: true, isIdentity: false, maxLength: null, precision: null, scale: null, default: null },
    { name: 'DurationMin', dataType: 'int', tsType: 'number', isNullable: true, isIdentity: false, maxLength: null, precision: 10, scale: 0, default: null },
    { name: 'Location', dataType: 'nvarchar', tsType: 'string', isNullable: true, isIdentity: false, maxLength: 128, precision: null, scale: null, default: null },
    { name: 'Theme', dataType: 'nvarchar', tsType: 'string', isNullable: true, isIdentity: false, maxLength: 128, precision: null, scale: null, default: null },
    { name: 'CoachUserId', dataType: 'int', tsType: 'number', isNullable: false, isIdentity: false, maxLength: null, precision: 10, scale: 0, default: null },
    { name: 'Notes', dataType: 'nvarchar', tsType: 'string', isNullable: true, isIdentity: false, maxLength: 1024, precision: null, scale: null, default: null },
    { name: 'CreatedAt', dataType: 'datetime2', tsType: 'string', isNullable: false, isIdentity: false, maxLength: null, precision: null, scale: null, default: '(sysutcdatetime())' },
    { name: 'UpdatedAt', dataType: 'datetime2', tsType: 'string', isNullable: true, isIdentity: false, maxLength: null, precision: null, scale: null, default: null },
  ],
  foreignKeys: [
    { name: 'FK_TrainingSessions_Users', column: 'CoachUserId', refTable: 'Users', refColumn: 'Id' },
  ],
} as const;

