// AUTO-GENERATED by SchemaExporter. DO NOT EDIT.
// Table: [dbo].[Users]

export interface Users {
  Id: number;
  UserName: string;
  Email: string;
  PasswordHash: string;
  Role: string;
  DisplayName: string | null;
  IsActive: boolean;
  CreatedAt: string;
  UpdatedAt: string | null;
}

export const Users_META = {
  schema: 'dbo',
  name: 'Users',
  primaryKey: ['Id'] as const,
  columns: [
    { name: 'Id', dataType: 'int', tsType: 'number', isNullable: false, isIdentity: true, maxLength: null, precision: 10, scale: 0, default: null },
    { name: 'UserName', dataType: 'nvarchar', tsType: 'string', isNullable: false, isIdentity: false, maxLength: 64, precision: null, scale: null, default: null },
    { name: 'Email', dataType: 'nvarchar', tsType: 'string', isNullable: false, isIdentity: false, maxLength: 256, precision: null, scale: null, default: null },
    { name: 'PasswordHash', dataType: 'nvarchar', tsType: 'string', isNullable: false, isIdentity: false, maxLength: 256, precision: null, scale: null, default: null },
    { name: 'Role', dataType: 'nvarchar', tsType: 'string', isNullable: false, isIdentity: false, maxLength: 16, precision: null, scale: null, default: '(N\'Player\')' },
    { name: 'DisplayName', dataType: 'nvarchar', tsType: 'string', isNullable: true, isIdentity: false, maxLength: 64, precision: null, scale: null, default: null },
    { name: 'IsActive', dataType: 'bit', tsType: 'boolean', isNullable: false, isIdentity: false, maxLength: null, precision: null, scale: null, default: '((1))' },
    { name: 'CreatedAt', dataType: 'datetime2', tsType: 'string', isNullable: false, isIdentity: false, maxLength: null, precision: null, scale: null, default: '(sysutcdatetime())' },
    { name: 'UpdatedAt', dataType: 'datetime2', tsType: 'string', isNullable: true, isIdentity: false, maxLength: null, precision: null, scale: null, default: null },
  ],
  foreignKeys: [
  ],
} as const;

